// ═══════════════════════════════════════════════════════════════
// BookEducate 8.0 — Premium Colorful Template (Typst Edition)
// ═══════════════════════════════════════════════════════════════

#let primary-dark = rgb("1B2A4A")
#let primary-accent = rgb("0EA5E9")
#let primary-light = rgb("E0F2FE")
#let secondary-accent = rgb("8B5CF6")
#let warm-accent = rgb("F59E0B")

#let example-bg = rgb("F0FDF4")
#let example-border = rgb("22C55E")
#let solution-bg = rgb("FFF7ED")
#let solution-border = rgb("F97316")

// ─── Document Setup ───
#let book(title: "BookEducate", author: "AI Synthetic Engine v8.0", body) = {
  set document(title: title, author: author)
  set page(
    paper: "a4",
    margin: (x: 1in, y: 1in),
    header: locate(loc => {
      let page-num = counter(page).at(loc).first()
      if calc.even(page-num) {
        align(left)[#text(size: 9pt, fill: primary-dark, weight: "bold")[BookEducate]]
      } else {
        align(right)[#text(size: 9pt, fill: luma(120))[Chapter Title]]
      }
      v(-0.5em)
      line(length: 100%, stroke: 0.5pt + primary-accent)
    }),
    footer: locate(loc => {
      let page-num = counter(page).at(loc).first()
      align(center)[#text(size: 9pt, fill: primary-accent, weight: "bold")[--- #page-num ---]]
    })
  )

  set text(font: "Linux Libertine", size: 12pt)
  set math.equation(numbering: "(1)")

  // ─── Headings Styling ───
  show heading.where(level: 1): it => {
    pagebreak(weak: true)
    v(1em)
    text(size: 28pt, fill: primary-dark, weight: "bold")[#it.body]
    v(0.2em)
    line(length: 100%, stroke: 2pt + primary-accent)
    v(1em)
  }

  show heading.where(level: 2): it => {
    v(1.5em, weak: true)
    text(size: 18pt, fill: primary-dark, weight: "bold")[#it.body]
    v(0.1em)
    line(length: 100%, stroke: 0.8pt + primary-accent)
    v(0.5em)
  }

  show heading.where(level: 3): it => {
    v(1em, weak: true)
    text(size: 14pt, fill: secondary-accent, weight: "bold")[#it.body]
    v(0.5em)
  }
  
  // ─── Lists ───
  set list(marker: text(fill: primary-accent)[•])

  // Title Page
  align(center)[
    #v(2cm)
    #line(length: 100%, stroke: 3pt + primary-accent)
    #v(1.5cm)
    #text(size: 42pt, fill: primary-dark, weight: "bold")[BookEducate] \
    #v(0.8cm)
    #text(size: 18pt, fill: secondary-accent)[Comprehensive Engineering Textbook] \
    #v(0.4cm)
    #text(size: 14pt, fill: luma(120))[Generated by BookEducate Synthetic Engine v8.0]
    #v(1.5cm)
    #line(length: 100%, stroke: 3pt + primary-accent)
    #v(2cm)
    #text(size: 14pt, fill: primary-dark)[#datetime.today().display()]
    #align(bottom)[
      #text(size: 10pt, fill: luma(120))[AI-Generated Educational Content — For Reference Use]
    ]
  ]

  pagebreak()

  // Outline (TOC)
  show outline.entry.where(level: 1): it => {
    v(0.5em, weak: true)
    text(fill: primary-dark, weight: "bold")[#it]
  }
  outline(depth: 2, indent: true)
  
  pagebreak()

  // Main body
  body
}

// ─── Custom Blocks (Example Problem / Solution) ───
#let exampleproblem(title: "Example Problem", body) = {
  v(1em)
  block(
    width: 100%,
    fill: example-bg,
    stroke: (left: 4pt + example-border),
    inset: 12pt,
    radius: 4pt,
    breakable: true, // Allows split across pages
  )[
    #text(weight: "bold", size: 13pt)[#title]
    #v(0.5em)
    #body
  ]
  v(1em)
}

#let solution(body) = {
  v(0.5em)
  block(
    width: 100%,
    fill: solution-bg,
    stroke: (left: 4pt + solution-border),
    inset: 10pt,
    radius: 4pt,
    breakable: true,
  )[
    #text(weight: "bold", fill: solution-border.darken(20%))[Solution:]
    #v(0.5em)
    #body
  ]
}

// ─── Injection Point ───
#show: book

$body$
